-- ATU Campus Event & Ticketing Management System (ETMS)
-- DATABASE DDL SCHEMA CREATION SCRIPTS

CREATE TABLE ETMS_USER (
    user_id NUMBER(10) NOT NULL,
    username VARCHAR2(50) NOT NULL,
    password_hash VARCHAR2(200) NOT NULL,
    email VARCHAR2(100),
    role VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (user_id),
    CONSTRAINT UQ_USERNAME UNIQUE (username),
    CONSTRAINT CHK_USER_ROLE CHECK (role IN ('ADMIN', 'ORGANIZER', 'ATTENDEE'))
);

CREATE TABLE ETMS_EVENT (
    event_id NUMBER(10) NOT NULL,
    title VARCHAR2(100) NOT NULL,
    location VARCHAR2(100) NOT NULL,
    event_date DATE NOT NULL,
    capacity NUMBER(5) NOT NULL,
    CONSTRAINT PK_EVENT PRIMARY KEY (event_id),
    CONSTRAINT CHK_EVENT_CAPACITY CHECK (capacity > 0)
);

CREATE TABLE ETMS_TICKET (
    ticket_id NUMBER(10) NOT NULL,
    event_id NUMBER(10) NOT NULL,
    type VARCHAR2(50) NOT NULL,
    price NUMBER(6) NOT NULL,
    CONSTRAINT PK_TICKET PRIMARY KEY (ticket_id),
    CONSTRAINT FK_TICKET_EVENT FOREIGN KEY (event_id) REFERENCES ETMS_EVENT(event_id)
);

CREATE TABLE ETMS_BOOKING (
    booking_id NUMBER(10) NOT NULL,
    user_id NUMBER(10) NOT NULL,
    ticket_id NUMBER(10) NOT NULL,
    quantity NUMBER(3) NOT NULL,
    CONSTRAINT PK_BOOKING PRIMARY KEY (booking_id),
    CONSTRAINT FK_BOOKING_USER FOREIGN KEY (user_id) REFERENCES ETMS_USER(user_id),
    CONSTRAINT FK_BOOKING_TICKET FOREIGN KEY (ticket_id) REFERENCES ETMS_TICKET(ticket_id),
    CONSTRAINT CHK_BOOKING_QTY CHECK (quantity > 0)
);

CREATE TABLE ETMS_PAYMENT (
    payment_id NUMBER(10) NOT NULL,
    booking_id NUMBER(10) NOT NULL,
    amount NUMBER(6) NOT NULL,
    payment_date DATE,
    CONSTRAINT PK_PAYMENT PRIMARY KEY (payment_id),
    CONSTRAINT FK_PAYMENT_BOOKING FOREIGN KEY (booking_id) REFERENCES ETMS_BOOKING(booking_id)
);s